example-sites/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');
Route::get('/info-contacto' , 'HomeController@detalle')->name('detalle');
          
Route::resource('/blog', 'PostController');

example-sites/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
}

example-sites/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

example-sites/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

example-sites/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Session;

use App\Models\Post;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){

        $posts = Post::all();
        
        return view ('index')->with('posts', $posts);
}

     public function detalle (){
        $nombre = 'Andres';
        $apellido = 'Torres';
        $tel = '47789627';
        $email = 'andres@hotmail.com';

        return view('detalle')
     ->with('nombre' , $nombre)
     ->with('apellido' , $apellido)
     ->with('tel' , $tel)
     ->with('email' , $email);

     }

    public function store(Request $request)
    {
    $post = new Post;

    $post->title = $request->title;
    $post->body = $request->body;
    $post->author = $request->author;
    $post->date = $request->date;
    $post->keywords = $request->keywords;


    }

     public function show(Post $post)
    {
        return view ('posts.show');
    }

   }

example-sites/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Session;

use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    
    public function index()
    {

        $posts = Post::all();
        
        return view ('posts.index')->with('posts', $posts);

    }


    public function create()
    {
        return view ('posts.create');
    }

    
    public function store(Request $request)
    {
    $post = new Post;

    $post->title = $request->title;
    $post->body = $request->body;
    $post->author = $request->author;
    $post->date = $request->date;
    $post->keywords = $request->keywords;

    $post->save();

    Session::flash('exito', 'Tu información se guardo correctamente');

    return redirect()->back();

    }

    
    public function show(Post $post)
    {
        return view ('posts.show');
    }

    
    public function edit(Post $post)
    {
        return view ('posts.edit');
    }

   
    public function update(Request $request, Post $post)
    {
        
    }

   
    public function destroy($id)
    {
     $post = Post::find($id);
     $post->delete();

     Session::flash('del','Tu publicacion se borro correctamente.');   

     return redirect()->back();
    }
}

example-sites/resources/views/detalle.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Titulo</title>

    </head>
    <body>

       <h1>Pantalla de Contacto</h1>
       <p>Nombre: {{ $nombre}}</p>
       <p>Apellido: {{ $apellido}}</p>
       <p>Tel: {{ $tel}}</p>
       <p>Correo: {{ $email}}</p>

    </body>
    </html>

example-sites/resources/views/index.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Mi página web</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="custom.css">

</head>
@if(Session::has('exito'))
<div style="background: lightgrey; color: #fff;">
    <p>{{ Session::get('exito') }}</p>
</div>
@endif

@if(Session::has('del'))
<div style="background: red; color: #fff;">
    <p>{{ Session::get('del') }}</p>
</div>
@endif

<body>


    
    <form method="POST" action="{{  route('blog.store')  }}">
    {{ csrf_field() }}
<section class="menu">
    
<div class="container">
    <div class="row">
    <div class="col-md-6">
        <h4>Titulo</h4>
    <input type="text" name="title" required="">
    <br><br>
    </div>
    <div class="col-md-6">
        <h4>Publicacion</h4>
    <textarea name="body" required="" rows="5"></textarea>
    <br><br>
    </div>
    <div class="col-md-6">
        <h4>Fecha de publicación</h4>
    <input type="date" name="date">
    <br><br>
    </div>
    <div class="col-md-6">
        <h4>Palabra(s) clave</h4>
    <input type="text" name="keywords">
    <br><br>
    </div>

    <button type="submit">Guardar datos</button>
    </form>
    
    </div>
</div>

</section>

<section class="portafolio">
    <div class="container">
        <div class="row">
            
                @foreach($posts as $post)
            <div class="col-md-3">
               <h1><strong>{{  $post->title  }}</strong></h1>
               <a>{{  $post->body  }}</a>
               <p>{{  $post->author  }}</p>
               <form method="POST" action="{{ route('blog.destroy', $post->id) }}">
               <button type="submit">Borrar</button>
               {{ csrf_field() }}
               {{ method_field('DELETE') }}
               </form>
               <hr style="color: blue;">
            </div>

               @endforeach
        </div>
    </div>
</section>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
      <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js">
    </script>

</body>

example-sites/resources/views/posts/index.blade.php
@if (Session::has('exito'))
<div style="background: lightgreen; color:#fff;">
    <p>{{ Session::get('exito') }}</p>
</div>
@endif

@if (Session::has('del'))
<div style="background: lightgreen; color:#fff;">
    <p>{{ Session::get('del') }}</p>
</div>
@endif

<form method="POST" action="{{ route ('blog.store') }}">
    {{ csrf_field () }}

    <label></label>Titulo</label><br>
    <input type="text" name="title" required=""><br>

    <label>Cuerpo</label><br>
    <textarea name="body" required="" rows="10"></textarea><br>

    <label>Autor</label><br>
    <input type="text" name="author"><br>

    <label>Fecha</label><br>
    <input type="date" name="date"><br>

    <label>Palabras clave</label>
    <input type="text" name="keywords"><br>
    <br>
    <br>
    <button type="submit">Guardar Datos</button>
</form>

@foreach($posts as $post)

    <h3>{{  $post->title  }}</h3>
    <p>{{  $post->body  }}</p>
    <form method="POST" action="{{ route('blog.destroy', $post->id) }}">
        <button type="submit">Borrar</button>
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
    </form>
    <hr style="color: blue;">

@endforeach